AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: fetch-resource
    Description: Performs retrieve operations in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/fetch-resource
    SourceCodeUrl: https://github.com/BIBSYSDEV/fetch-resource

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain


Resources:

  FetchResourceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      Cors:
        AllowCredentials: true
        AllowOrigin: 'localhost'

  FetchResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./fetch_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /{identifier}
            Method: GET
            RestApiId: !Ref FetchResourceApi
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable

  FetchResourceBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref FetchResourceApi
      Stage: !Ref FetchResourceApi.Stage
