AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: fetch-resource
    Description: Performs retrieve operations in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/fetch-resource
    SemanticVersion: 0.0.3
    SourceCodeUrl: https://github.com/BIBSYSDEV/fetch-resource

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data

Globals:
  Api:
    Name: Prod

Resources:

  FetchResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./fetch_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /resources/{identifier}
            Method: GET
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region

