class Constants:
    ENV_VAR_REGION = 'REGION'
    ENV_VAR_TABLE_NAME = 'TABLE_NAME'

    EVENT_BODY = 'body'

    OPERATION_RETRIEVE = 'RETRIEVE'

    JSON_ATTRIBUTE_NAME_OPERATION = 'operation'
    JSON_ATTRIBUTE_NAME_RESOURCE = 'resource'

    RESPONSE_STATUS_CODE = 'statusCode'
    RESPONSE_BODY = 'body'

    DDB_RESPONSE_ATTRIBUTE_NAME_ITEMS = 'Items'

    DDB_FIELD_RESOURCE_IDENTIFIER = 'resource_identifier'

    ERROR_MISSING_EVENT = 'Missing event'
